### ISSUE TITLE
Ambiguïté dans l'horaire du Esquina Café

### ISSUE THREAD

**Issue by normcyr** [simark/velo-espresso#4]
Il y a ambiguïté dans l'horaire du Esquina Café. Sur leur page Facebook, il est mentionné que l'heure d'ouverture est 7:30 tandis que sur leur site web, il est mentionné 8:00.

Je vais les contacter pour clarifier le tout.

Je suggère qu'on attende avant d'y aller.

**Comment by simark** [comment]
Oh, merci d'avoir vérifié.

**Comment by normcyr** [comment]
Ils m'ont confirmé par FB Messenger que ça ouvrait bel et bien à 7:30.

![screenshot](https://user-images.githubusercontent.com/9942439/64978759-423baa80-d884-11e9-8d4c-35cdfb99cfd5.png)

**Comment by simark** [comment]
Excellent travail!
